export const FRAME_IDS = [
  "hero",
  "executive-summary",
  "about-flex",
  "context",
  "business-context",
  "best-practices",
  "current-vs-target",
  "challenge",
  "objective",
  "user-journeys",
  "information-architecture",
  "perspective",
  "design-philosophy",
  "style-directions",
  "whats-included",
  "website",
  "social-media",
  "project-management",
  "pricing",
  "timeline-investment",
  "governance",
  "cta",
] as const;

export const SECTION_NAMES = [
  "Hero",
  "Executive Summary",
  "About Flex",
  "Context",
  "Business Context",
  "Best Practices",
  "Current vs Target",
  "Challenge",
  "Objective",
  "User Journeys",
  "Information Architecture",
  "Perspective",
  "Design Philosophy",
  "Style Directions",
  "What's Included",
  "Website",
  "Social Media",
  "Project Management",
  "Pricing",
  "Timeline & Investment",
  "Governance",
  "Call to Action",
] as const;
