export const FRAME_IDS = [
  "hero",
  "executive-summary",
  "about-flex",
  "context",
  "business-context",
  "best-practices",
  "current-vs-target",
  "challenge",
  "objective",
  "user-journeys",
  "information-architecture",
  "perspective",
  "design-philosophy",
  "whats-included",
  "website",
  "social-media",
  "project-management",
  "timeline-investment",
  "governance",
] as const;

export const SECTION_NAMES = [
  "Hero",
  "Executive Summary",
  "About Flex",
  "Context",
  "Business Context",
  "Best Practices",
  "Current vs Target",
  "Challenge",
  "Objective",
  "User Journeys",
  "Information Architecture",
  "Perspective",
  "Design Philosophy",
  "What's Included",
  "Website",
  "Social Media",
  "Project Management",
  "Timeline & Investment",
  "Governance",
] as const;
